### ISSUE TITLE
Clicking login crashes the game

### ISSUE THREAD

**Issue by theolaval** [Axieum/Chatter#39]
**Describe the bug**
When i want to whrite on my server, i have no message and a big error on my console.
my error: 

```
[12:03:57] [Server thread/INFO]: Skoiyo joined the game
[12:04:00] [Server thread/FATAL]: Error executing task on Server
java.lang.ClassCastException: net.minecraft.class_2585 cannot be cast to java.lang.String
        at net.minecraft.class_3244.redirect$zjd000$onChatMessage(class_3244.java:3634) ~[intermediary-server.jar:?]
        at net.minecraft.class_3244.method_31286(class_3244.java:1201) ~[intermediary-server.jar:?]
        at net.minecraft.class_3244.method_31284(class_3244.java:314) ~[intermediary-server.jar:?]
        at net.minecraft.class_3244.method_31280(class_3244.java:324) ~[intermediary-server.jar:?]
        at net.minecraft.class_3738.run(class_3738.java:18) ~[intermediary-server.jar:?]
        at net.minecraft.class_1255.method_18859(class_1255.java:144) ~[intermediary-server.jar:?]
        at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:761) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:155) ~[intermediary-server.jar:?]
        at net.minecraft.class_1255.method_16075(class_1255.java:118) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:743) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:737) ~[intermediary-server.jar:?]
        at net.minecraft.class_1255.method_5383(class_1255.java:103) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:721) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:674) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257) ~[intermediary-server.jar:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_281]
```

**Comment by Skoiyo** [comment]
![image](https://user-images.githubusercontent.com/47790793/120920597-d8021380-c6bf-11eb-844c-33ce708d70a6.png)
And i don't know if it's normal this
